### ISSUE TITLE
Friktion TVL not updating between High/Low

### ISSUE THREAD

**Issue by flodef** [Avaulto/Compact-DeFi#2]
In Defi / Volt Strategies : 
When switching from high volt to low volt, and vice versa, the green bar showing deposit is not updating !
For a different TVL, the green bar stays the same
![Screenshot 2023-01-05 22 52 03](https://user-images.githubusercontent.com/9675304/210887420-051b1b01-cd3b-4b80-b483-ed7b572672e9.png)
![Screenshot 2023-01-05 22 51 50](https://user-images.githubusercontent.com/9675304/210887423-3c155bf8-062f-461c-bee1-20682a21765c.png)

**Comment by AC-devon** [comment]
friktion is deprecated :(
closing
