### ISSUE TITLE
Friktion volt logo not showing up

### ISSUE THREAD

**Issue by flodef** [Avaulto/Compact-DeFi#3]
The Friktion volt logo is not what it should be (SOL logo for SOL, BTC logo for BTC, etc)

![Screenshot 2023-01-05 22 52 032](https://user-images.githubusercontent.com/9675304/210892970-d601d1f1-146b-4966-a902-3386da18401e.png)

**Comment by AC-devon** [comment]
same as https://github.com/Avaulto/Compact-DeFi/issues/4
closed :)
