### ISSUE TITLE
Volt voltage is not displayed

### ISSUE THREAD

**Issue by flodef** [Avaulto/Compact-DeFi#4]
Because Volt voltage (High / Low) is not written, it's confusing to know which is which apart from the APY (can be misleading).
I would put which voltage next to SOL title ==> SOL (low) or SOL (high), otherwise, the only indication is the APY.

![Screenshot 2023-01-05 22 52 032](https://user-images.githubusercontent.com/9675304/210893363-e2029902-e7c8-42ff-b0db-792d27de6720.png)

**Comment by AC-devon** [comment]
had an issue with the "skeleton" placeholder, 
problem solved 👍🏻
