### ISSUE TITLE
Deposit / Withdraw instead of Select

### ISSUE THREAD

**Issue by flodef** [Avaulto/Compact-DeFi#5]
Instead of "Select Volt", I would prefer to have "Deposit / Withdraw", otherwise, I find it's confusing: I would like to deposit or withdraw, and I need to click on "Select" ?!

![Screenshot 2023-01-05 23 39 212](https://user-images.githubusercontent.com/9675304/210893901-442d01e5-299b-4355-8920-a950ae509145.png)

**Comment by AC-devon** [comment]
first, you select a vault, then you decide if you wish to deposit or withdraw.
if we look at friktion, they always have "deposit" first button, but I believe the intention here isn't to represent all users
![image](https://user-images.githubusercontent.com/11775780/212496681-61fe2efb-18d7-41b3-a521-bc92c866aa21.png)

Therefore i find it more logical to select a value than choose the action

**Comment by flodef** [comment]
I get your point.
In Friktion, when you arrive, there is the "Deposit" button. If you have already deposited before, there is a "Manage" button. I find it more appealing and intuitive... as it's incite me to deposit!
But "Select Volt" is also fine and it's your style so it's all good :-D
